### ISSUE TITLE
Desktop Notifications not working

### ISSUE THREAD

**Issue by webmastir** [bipycxp/TwitchLive#1]
~~Win 10 + Chrome v 52.0.2743.116 m~~

~~I've tried this on 3 different computers (Win 8.1 & 2 Win 10 (pro) and (enterprise)). All do not show~~~~notifications when a streamer is live. It just gives you a number count on the extension toolbar icon.~~

~~Is this expected design for "notifications?~~

Edit: **nvm**. It works. I kept missing the damn notification for some reason.

**Comment by bipycxp** [comment]
Problem is resolved?

**Comment by webmastir** [comment]
Yeah, it was a a stupid user error.

**Comment by bipycxp** [comment]
Can you describe it?)

**Comment by webmastir** [comment]
My stupidity? I mean, sure, I guess. It's pretty much what I edited in my initial post/comment. 

I thought the desktop notifications would stick around longer but chrome kept dismissing them after a short interval. Thus, I thought it wasn't notifying me at all until I finally saw that it was.
