### ISSUE TITLE
Streams Live no longer updating, showing loading icon forever; Import Following now results in an Error

### ISSUE THREAD

**Issue by ScorelessPine** [bipycxp/TwitchLive#13]
For the past week or so, the number of live streams no longer seems to update properly or show which streams are live at all, simply being stuck on a loading icon forever. I have occasionally seen it working again, but it was only for a short time, and it has since stopped again. I am not the only one with this issue, according to the "support" section of the extension's app page: https://chrome.google.com/webstore/detail/twitch-live/imcjibojeokeogfofjgaajlobobagbeg?hl=en.

Users "CritikalCanadian" "Morten" and "Ryan Richardson" are also having the same problem and have posted such.

Ryan also mentioned that when attempting to import following, the extension will report an error instead, which I have also noticed, but I can only assume that the cause is the same as the main issue. Attached below are images showing both issues.

![image](https://user-images.githubusercontent.com/28274052/81251896-4b2ae900-8fd9-11ea-831b-c4305ca7741f.png)

![image](https://user-images.githubusercontent.com/28274052/81251953-77df0080-8fd9-11ea-9870-94a6912941a2.png)

**Comment by lecram90** [comment]
Same issue here.
After a little digging I found out that the previous Twitch API v5 is now deprecated (as of April 30, 2020) and is replaced by "The new Twitch API".

Old Twitch API v5: https://dev.twitch.tv/docs/v5
New Twitch API: https://dev.twitch.tv/docs/api
Announcement: https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

Hope this helps in fixing this plugin :)

**Comment by bipycxp** [comment]
Hey guys! Yes, this Twitch API update added required OAuth for some API requests, which this plugin is using. So, to fix it, need to implement OAuth process, but I don't have a time for it :(

**Comment by webmastir** [comment]
Bummer but understandable. It was a cool extension while it lasted. Thanks anyway, bipycxp!

**Comment by DarthJahus** [comment]
But can you implement OAuth without requiring the user to get himself an API token? You can't integrate your own token, since it's a secret.

Twitch really made it hard for developers to query data that should be publicly available.

**Comment by Remco0o** [comment]
> Hey guys! Yes, this Twitch API update added required OAuth for some API requests, which this plugin is using. So, to fix it, need to implement OAuth process, but I don't have a time for it :(

When do you hav time for it i really like your extension

**Comment by K0FFing** [comment]
Todays February 2023 and the problem prersist sadly 
last pluging update: 12 August 2019

3 years, 5 months, 3 weeks, 1 day
1271 days

**Comment by ScorelessPine** [comment]
For any/all of you who still want a functionality like what this extension used to provide, I've since been using Gumbo: Twitch Companion instead. I'm going to close this issue as not planned due to the period of time since the original issue and the dev's comment.
