### ISSUE TITLE
No Desktop Notification

### ISSUE THREAD

**Issue by Volpey** [bipycxp/TwitchLive#3]
Hey, I installed the extension yesterday but I don't get notifications.

I even activated the sound option to not miss any notifications, the number just changes.

Windows 10, Chrome Version 54.0.2840.99 m (64-bit).

Edit: Now I have gotten one notification and that was really late. About 1 hour.

Edit 2: It seems like i only get notifications for streams I have marked as favorite? Is there an option to get notification for all strems I follow?

**Comment by bipycxp** [comment]
@Volpey, in current version you can get notifications only for favorite streams. Maybe, need to rename `Favorite` button to `Notify me` or like that.

Thanks for your issue ❤️ and sorry for late response :)

**Comment by bipycxp** [comment]
Fix in **2.0.6** version.

**Comment by FlorianHoelzel** [comment]
Still no possibility to get notifications for every stream I am following?

**Comment by bipycxp** [comment]
@Volpey, you get notification only if channel marked "Favorite/Notify me". If you want get notifications for every following channel - mark all of them.

I'm working on a major update of Twitch Live. Hope, the new version will have a more user-friendly and intuitive interface.
